pipeline {
    // agent any
    agent {
        docker {
            image 'maven:3.8.6-openjdk-8-slim'
            args '-v /root/.m2:/root/.m2'
        }
    }
    // tools { 
    //     maven 'Maven3' 
    //     jdk 'jdk8' 
    // }

    stages {
        stage('build') {
            steps {
                echo 'Building the application...'
                sh 'mvn -B -DskipTests clean package'
            }
        }

        stage('test') {
            steps {
                echo 'Testing the application...'
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('deliver') {
            steps {
                echo 'Deliver the application...'
                sh './jenkins/scripts/deliver.sh'
            }
        }

        stage('upload to nexus') {
            steps {
                script {
                    echo 'Uploading the application to nexus...'
                    def mavenPom = readMavenPom file: 'pom.xml'
                    nexusArtifactUploader artifacts: [
                        [
                            artifactId: "${mavenPom.artifactId}", 
                            classifier: '', 
                            file: "target/${mavenPom.name}-${mavenPom.version}.${mavenPom.packaging}", 
                            type: "${mavenPom.packaging}"
                        ]
                    ], 
                    credentialsId: 'nexus', 
                    groupId: "${mavenPom.groupId}", 
                    nexusUrl: 'localhost:8881', 
                    nexusVersion: 'nexus3', 
                    protocol: 'http', 
                    repository: 'simple-maven-app-release', 
                    version: '1.0'
                }
            }
        }
    }

    post {
        success {
            echo "Successful pipeline"
        }
    }
}
