pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('build') {
            steps {
                echo 'Building the application...'
                // sh 'mvn -B -DskipTests clean package'
            }
        }

        stage('test') {
            steps {
                echo 'Testing the application...'
                // sh 'mvn test'
            }
            // post {
            //     always {
            //         junit 'target/surefire-reports/*.xml'
            //     }
            // }
        }

        stage('deliver') {
            steps {
                echo 'Deliver the application...'
                // sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
