pipeline {
    // agent any
    agent {
        docker {
            image 'maven:3.8.6-openjdk-8-slim'
            args '-v /root/.m2:/root/.m2'
        }
    }
    // tools { 
    //     maven 'Maven3' 
    //     jdk 'jdk8' 
    // }

    stages {
        stage('build') {
            steps {
                echo 'Building the application...'
                sh 'mvn -B -DskipTests clean package'
            }
        }

        stage('test') {
            steps {
                echo 'Testing the application...'
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('deliver') {
            steps {
                echo 'Deliver the application...'
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }

    post {
        success {
            echo "Successful pipeline"
        }
    }
}
